import { describe, expect, it } from 'vitest'
import { detectDialect, parseDdl, splitStatements, unquoteIdentifier } from './ddl-parse.js'

describe('splitStatements', () => {
  it('세미콜론으로 나누고 각 문장의 시작 줄 번호를 남긴다', () => {
    const s = splitStatements('CREATE TABLE A (X INT);\nCREATE TABLE B (Y INT);')
    expect(s).toHaveLength(2)
    expect(s[0]!.line).toBe(1)
    expect(s[1]!.line).toBe(2)
  })

  it('줄 주석과 블록 주석을 제거하되 줄 번호는 유지한다', () => {
    const s = splitStatements('-- 머리말\n/* 블록\n   주석 */\nCREATE TABLE A (X INT);')
    expect(s).toHaveLength(1)
    expect(s[0]!.text).toContain('CREATE TABLE A')
    expect(s[0]!.line).toBe(4)
  })

  it('문자열 리터럴 안의 세미콜론·주석 기호로 나누지 않는다', () => {
    const s = splitStatements("COMMENT ON TABLE A IS 'a;b -- c';\nCREATE TABLE B (Y INT);")
    expect(s).toHaveLength(2)
    expect(s[0]!.text).toContain("'a;b -- c'")
  })

  it('문자열 안의 작은따옴표 이스케이프를 문자열의 일부로 본다', () => {
    const s = splitStatements("COMMENT ON TABLE A IS 'it''s; ok';\nCREATE TABLE B (Y INT);")
    expect(s).toHaveLength(2)
  })

  it('Oracle 스크립트의 / 구분자로도 나눈다', () => {
    const s = splitStatements('CREATE TABLE A (X INT)\n/\nCREATE TABLE B (Y INT)\n/')
    expect(s).toHaveLength(2)
  })

  it('빈 문장을 버린다', () => {
    expect(splitStatements(';;\n  \n;')).toEqual([])
  })

  it('CRLF 줄바꿈에서도 Oracle / 구분자와 줄 번호가 정상이다', () => {
    const s = splitStatements('CREATE TABLE A (X INT)\r\n/\r\nCREATE TABLE B (Y INT)\r\n/')
    expect(s).toHaveLength(2)
    expect(s[0]!.line).toBe(1)
    expect(s[1]!.line).toBe(3)
  })

  it('CRLF 줄바꿈에서 줄 주석이 문장을 삼키지 않는다', () => {
    const s = splitStatements('-- 머리말\r\nCREATE TABLE A (X INT);\r\nCREATE TABLE B (Y INT);')
    expect(s).toHaveLength(2)
    expect(s[0]!.line).toBe(2)
  })
})

describe('unquoteIdentifier', () => {
  it('방언별 따옴표를 벗긴다', () => {
    expect(unquoteIdentifier('"MBR"')).toBe('MBR')
    expect(unquoteIdentifier('`MBR`')).toBe('MBR')
    expect(unquoteIdentifier('[MBR]')).toBe('MBR')
    expect(unquoteIdentifier('MBR')).toBe('MBR')
  })

  it('스키마 접두사를 떼고 마지막 조각만 남긴다', () => {
    expect(unquoteIdentifier('public.MBR')).toBe('MBR')
    expect(unquoteIdentifier('"public"."MBR"')).toBe('MBR')
    expect(unquoteIdentifier('[dbo].[MBR]')).toBe('MBR')
    expect(unquoteIdentifier('SCOTT.MBR')).toBe('MBR')
  })

  it('따옴표 안의 점은 구분자가 아니다', () => {
    expect(unquoteIdentifier('"a.b"')).toBe('a.b')
  })

  it('이스케이프된 따옴표를 되돌린다', () => {
    expect(unquoteIdentifier('"a""b"')).toBe('a"b')
  })
})

describe('detectDialect', () => {
  it('특징 토큰으로 방언을 맞힌다', () => {
    expect(detectDialect('CREATE TABLE `a` (id INT AUTO_INCREMENT);')).toBe('mysql')
    expect(detectDialect('CREATE TABLE a (id NUMBER(10), nm VARCHAR2(10), memo CLOB);')).toBe('oracle')
    expect(detectDialect('CREATE TABLE [a] ([id] INT IDENTITY(1,1), nm NVARCHAR(10));')).toBe('mssql')
    expect(detectDialect('CREATE TABLE a (id serial, doc jsonb, at timestamptz);')).toBe('postgresql')
  })

  it('근거가 없으면 null을 준다', () => {
    expect(detectDialect('CREATE TABLE a (id INT, nm VARCHAR(10));')).toBeNull()
  })
})

describe('parseDdl', () => {
  it('인식하지 못한 문장을 skipped에 키워드·줄 번호와 함께 남긴다', () => {
    const r = parseDdl('GRANT SELECT ON a TO b;\nCREATE SEQUENCE s;')
    expect(r.skipped.map((s) => s.keyword)).toEqual(['GRANT', 'CREATE SEQUENCE'])
    expect(r.skipped[0]!.line).toBe(1)
    expect(r.skipped[1]!.line).toBe(2)
    expect(r.skipped[0]!.excerpt).toContain('GRANT SELECT')
  })

  it('빈 입력에서 빈 결과를 준다', () => {
    expect(parseDdl('')).toEqual({
      tables: [], constraints: [], indexes: [], comments: [], skipped: [],
    })
  })
})

describe('parseDdl — CREATE TABLE', () => {
  it('컬럼의 타입·NOT NULL·DEFAULT를 읽는다', () => {
    const r = parseDdl(`
      CREATE TABLE MBR (
        MBR_NO bigint NOT NULL,
        MBR_NM varchar(100),
        REG_DT timestamp DEFAULT now(),
        PRIMARY KEY (MBR_NO)
      );`)
    expect(r.tables).toHaveLength(1)
    const t = r.tables[0]!
    expect(t.name).toBe('MBR')
    expect(t.columns.map((c) => c.name)).toEqual(['MBR_NO', 'MBR_NM', 'REG_DT'])
    expect(t.columns[0]).toMatchObject({ rawType: 'bigint', notNull: true, defaultValue: null })
    expect(t.columns[1]).toMatchObject({ rawType: 'varchar(100)', notNull: false })
    expect(t.columns[2]!.defaultValue).toBe('now()')
    expect(r.constraints).toContainEqual({ kind: 'pk', table: 'MBR', columns: ['MBR_NO'] })
  })

  it('인라인 PRIMARY KEY를 컬럼에 표시한다', () => {
    const r = parseDdl('CREATE TABLE A (ID bigint PRIMARY KEY, NM varchar(10));')
    expect(r.tables[0]!.columns[0]!.inlinePk).toBe(true)
    expect(r.tables[0]!.columns[1]!.inlinePk).toBe(false)
  })

  it('방언별 자동증가를 인식한다', () => {
    expect(parseDdl('CREATE TABLE A (ID INT AUTO_INCREMENT);')
      .tables[0]!.columns[0]!.autoIncrement).toBe(true)
    expect(parseDdl('CREATE TABLE A (ID INT IDENTITY(1,1));')
      .tables[0]!.columns[0]!.autoIncrement).toBe(true)
    expect(parseDdl('CREATE TABLE A (ID bigint GENERATED BY DEFAULT AS IDENTITY);')
      .tables[0]!.columns[0]!.autoIncrement).toBe(true)
    expect(parseDdl('CREATE TABLE A (ID serial);')
      .tables[0]!.columns[0]!.autoIncrement).toBe(true)
  })

  it('테이블 수준 UNIQUE·FOREIGN KEY를 제약으로 뽑는다', () => {
    const r = parseDdl(`
      CREATE TABLE ORD (
        ORD_NO bigint NOT NULL,
        MBR_NO bigint NOT NULL,
        CONSTRAINT PK_ORD PRIMARY KEY (ORD_NO),
        CONSTRAINT UX_ORD_01 UNIQUE (MBR_NO, ORD_NO),
        CONSTRAINT FK_ORD_MBR FOREIGN KEY (MBR_NO) REFERENCES MBR (MBR_NO)
      );`)
    expect(r.constraints).toContainEqual({ kind: 'pk', table: 'ORD', columns: ['ORD_NO'] })
    expect(r.constraints).toContainEqual({
      kind: 'unique', table: 'ORD', name: 'UX_ORD_01', columns: ['MBR_NO', 'ORD_NO'],
    })
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: 'FK_ORD_MBR',
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: ['MBR_NO'],
    })
  })

  it('인라인 REFERENCES를 FK 제약으로 만든다', () => {
    const r = parseDdl('CREATE TABLE ORD (MBR_NO bigint REFERENCES MBR (MBR_NO));')
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: null,
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: ['MBR_NO'],
    })
  })

  it('따옴표 식별자와 스키마 접두사를 벗긴다', () => {
    const r = parseDdl('CREATE TABLE "public"."MBR" ("MBR NO" bigint);')
    expect(r.tables[0]!.name).toBe('MBR')
    expect(r.tables[0]!.columns[0]!.name).toBe('MBR NO')
  })

  it('MySQL 인라인 COMMENT를 컬럼에 담는다', () => {
    const r = parseDdl("CREATE TABLE A (ID INT COMMENT '회원번호 - 식별자') ENGINE=InnoDB;")
    expect(r.tables[0]!.columns[0]!.comment).toBe('회원번호 - 식별자')
  })

  it('CHECK 제약을 건너뛰고 경고한다', () => {
    const r = parseDdl("CREATE TABLE A (ST varchar(2), CHECK (ST IN ('01','02')));")
    expect(r.tables[0]!.columns.map((c) => c.name)).toEqual(['ST'])
    expect(r.skipped.some((s) => s.keyword === 'CHECK')).toBe(true)
  })

  it('컬럼 타입의 괄호 안 쉼표에 속지 않는다', () => {
    const r = parseDdl('CREATE TABLE A (AMT numeric(12,3), NM varchar(10));')
    expect(r.tables[0]!.columns.map((c) => c.rawType)).toEqual(['numeric(12,3)', 'varchar(10)'])
  })

  it('꼬리 절(테이블스페이스·ENGINE·파티션)을 건너뛴다', () => {
    const r = parseDdl('CREATE TABLE A (ID INT) TABLESPACE users;')
    expect(r.tables[0]!.columns.map((c) => c.name)).toEqual(['ID'])
  })

  it('GENERATED … AS IDENTITY의 DEFAULT를 기본값으로 오인하지 않는다', () => {
    const byDefault = parseDdl('CREATE TABLE A (ID bigint GENERATED BY DEFAULT AS IDENTITY);')
      .tables[0]!.columns[0]!
    expect(byDefault.autoIncrement).toBe(true)
    expect(byDefault.defaultValue).toBeNull()

    const always = parseDdl('CREATE TABLE A (ID bigint GENERATED ALWAYS AS IDENTITY);')
      .tables[0]!.columns[0]!
    expect(always.autoIncrement).toBe(true)
    expect(always.defaultValue).toBeNull()
  })

  it('IDENTITY 절을 걷어내도 진짜 DEFAULT는 그대로 읽는다', () => {
    const c = parseDdl("CREATE TABLE A (ST varchar(2) DEFAULT '01' NOT NULL);").tables[0]!.columns[0]!
    expect(c.defaultValue).toBe("'01'")
    expect(c.notNull).toBe(true)
  })

  it('IDENTITY와 진짜 DEFAULT가 함께 와도 각각 옳게 읽는다', () => {
    const c = parseDdl("CREATE TABLE A (ID bigint GENERATED BY DEFAULT AS IDENTITY, ST varchar(2) DEFAULT 'X');")
      .tables[0]!.columns
    expect(c[0]!.defaultValue).toBeNull()
    expect(c[1]!.defaultValue).toBe("'X'")
  })

  it('문자열 리터럴 안의 키워드가 구조 플래그를 뒤집지 않는다', () => {
    const c = parseDdl("CREATE TABLE A (ID INT COMMENT 'legacy identity primary key not null candidate');")
      .tables[0]!.columns[0]!
    expect(c.notNull).toBe(false)
    expect(c.inlinePk).toBe(false)
    expect(c.autoIncrement).toBe(false)
    expect(c.comment).toBe('legacy identity primary key not null candidate')
  })

  it('문자열 리터럴 안의 REFERENCES가 가짜 FK를 만들지 않는다', () => {
    const r = parseDdl("CREATE TABLE A (NOTE varchar(50) DEFAULT 'REFERENCES old system (v1)');")
    expect(r.constraints).toEqual([])
    expect(r.tables[0]!.columns[0]!.defaultValue).toBe("'REFERENCES old system (v1)'")
  })

  it('문자열 안의 종결 키워드가 DEFAULT 값을 일찍 끊지 않는다', () => {
    const c = parseDdl("CREATE TABLE A (ST varchar(10) DEFAULT 'a COMMENT b' NOT NULL);")
      .tables[0]!.columns[0]!
    expect(c.defaultValue).toBe("'a COMMENT b'")
    expect(c.notNull).toBe(true)
  })

  it('진짜 구조 키워드는 여전히 인식한다(대조군)', () => {
    const c = parseDdl("CREATE TABLE A (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '설명');")
      .tables[0]!.columns[0]!
    expect(c.notNull).toBe(true)
    expect(c.inlinePk).toBe(true)
    expect(c.autoIncrement).toBe(true)
    expect(c.comment).toBe('설명')
  })

  it('진짜 인라인 REFERENCES는 여전히 잡는다(대조군)', () => {
    const r = parseDdl('CREATE TABLE ORD (MBR_NO bigint REFERENCES MBR (MBR_NO));')
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: null,
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: ['MBR_NO'],
    })
  })

  it('MySQL의 꼬리 테이블 COMMENT를 잡는다', () => {
    const r = parseDdl("CREATE TABLE MBR (ID INT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='회원';")
    expect(r.comments).toContainEqual({ table: 'MBR', column: null, text: '회원' })
  })

  it('= 없는 형태도 잡는다', () => {
    const r = parseDdl("CREATE TABLE MBR (ID INT) COMMENT '회원 - 설명';")
    expect(r.comments).toContainEqual({ table: 'MBR', column: null, text: '회원 - 설명' })
  })

  it('컬럼 정의 안의 COMMENT를 테이블 코멘트로 오인하지 않는다(대조군)', () => {
    const r = parseDdl("CREATE TABLE MBR (ID INT COMMENT '회원번호');")
    expect(r.comments).toEqual([])
    expect(r.tables[0]!.columns[0]!.comment).toBe('회원번호')
  })
})

describe('parseDdl — 나머지 문장', () => {
  it('ALTER TABLE ADD CONSTRAINT로 분리된 PK·UNIQUE·FK를 잡는다', () => {
    const r = parseDdl(`
      ALTER TABLE MBR ADD CONSTRAINT PK_MBR PRIMARY KEY (MBR_NO);
      ALTER TABLE ORD ADD CONSTRAINT UX_ORD UNIQUE (ORD_NM);
      ALTER TABLE ORD ADD CONSTRAINT FK_ORD_MBR FOREIGN KEY (MBR_NO)
        REFERENCES MBR (MBR_NO) ON DELETE CASCADE;`)
    expect(r.constraints).toContainEqual({ kind: 'pk', table: 'MBR', columns: ['MBR_NO'] })
    expect(r.constraints).toContainEqual({ kind: 'unique', table: 'ORD', name: 'UX_ORD', columns: ['ORD_NM'] })
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: 'FK_ORD_MBR',
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: ['MBR_NO'],
    })
  })

  it('CREATE INDEX와 CREATE UNIQUE INDEX를 구분해 잡는다', () => {
    const r = parseDdl(`
      CREATE INDEX IX_MBR_01 ON MBR (MBR_NM);
      CREATE UNIQUE INDEX UX_MBR_01 ON "public"."MBR" (MBR_NM DESC, REG_DT);`)
    expect(r.indexes).toContainEqual({ table: 'MBR', name: 'IX_MBR_01', columns: ['MBR_NM'], unique: false })
    expect(r.indexes).toContainEqual({
      table: 'MBR', name: 'UX_MBR_01', columns: ['MBR_NM', 'REG_DT'], unique: true,
    })
  })

  it('COMMENT ON TABLE·COLUMN을 잡고 이스케이프를 되돌린다', () => {
    const r = parseDdl(`
      COMMENT ON TABLE MBR IS '회원';
      COMMENT ON COLUMN MBR.MBR_NO IS '회원번호 - it''s';`)
    expect(r.comments).toContainEqual({ table: 'MBR', column: null, text: '회원' })
    expect(r.comments).toContainEqual({ table: 'MBR', column: 'MBR_NO', text: "회원번호 - it's" })
  })

  it('ALTER TABLE의 인식 못 하는 형태는 건너뛴다', () => {
    const r = parseDdl('ALTER TABLE MBR ENABLE ROW MOVEMENT;')
    expect(r.constraints).toEqual([])
    expect(r.skipped.some((s) => s.keyword === 'ALTER TABLE')).toBe(true)
  })

  it('트리거·시퀀스·뷰·권한을 건너뛴다', () => {
    const r = parseDdl(`
      CREATE SEQUENCE SEQ_MBR START WITH 1;
      CREATE VIEW V_MBR AS SELECT * FROM MBR;
      GRANT SELECT ON MBR TO APP;`)
    expect(r.skipped.map((s) => s.keyword)).toEqual(['CREATE SEQUENCE', 'CREATE VIEW', 'GRANT'])
  })
})

describe('parseDdl — 나머지 문장의 문자열 리터럴 오탐 점검', () => {
  it('COMMENT 텍스트 안의 구조 키워드(TABLE/COLUMN/IS)가 파싱을 흔들지 않는다', () => {
    const r = parseDdl(
      "COMMENT ON TABLE MBR IS 'This TABLE IS the COLUMN registry, see MBR.OTHER_COL IS unused';",
    )
    expect(r.comments).toContainEqual({
      table: 'MBR', column: null,
      text: 'This TABLE IS the COLUMN registry, see MBR.OTHER_COL IS unused',
    })
  })

  it('CHECK 절 리터럴 안의 PRIMARY KEY/FOREIGN KEY 텍스트를 제약으로 오인하지 않는다', () => {
    const r = parseDdl(
      "ALTER TABLE MBR ADD CONSTRAINT CK_MBR CHECK (NOTE = 'PRIMARY KEY (X) FOREIGN KEY (Y) REFERENCES Z (W)');",
    )
    expect(r.constraints).toEqual([])
    expect(r.skipped.some((s) => s.keyword === 'ALTER TABLE')).toBe(true)
  })

  it('명시적 참조 컬럼 없는 FK에서 REFERENCES 뒤 절(ON DELETE 등)이 refTable에 섞이지 않는다', () => {
    const r = parseDdl(
      'ALTER TABLE ORD ADD CONSTRAINT FK_ORD_MBR FOREIGN KEY (MBR_NO) REFERENCES MBR ON DELETE CASCADE;',
    )
    const fk = r.constraints.find((c) => c.kind === 'fk')
    expect(fk).toBeDefined()
    expect(fk!.refTable).toBe('MBR')
  })

  // Minor: Oracle의 RELY는 ENABLE 없이 단독으로 올 수 있는 제약 상태 키워드다.
  it('Oracle의 RELY 같은 단독 제약 상태 키워드도 refTable에 섞이지 않는다', () => {
    const r = parseDdl('ALTER TABLE ORD ADD CONSTRAINT FK1 FOREIGN KEY (X) REFERENCES MBR RELY;')
    expect(r.constraints[0]).toMatchObject({ refTable: 'MBR' })
  })

  it('참조 컬럼을 생략해도 꼬리 절이 부모 테이블 이름에 섞이지 않는다', () => {
    const r = parseDdl('ALTER TABLE ORD ADD CONSTRAINT FK1 FOREIGN KEY (MBR_NO) REFERENCES MBR ON DELETE CASCADE;')
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: 'FK1',
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: [],
    })
  })

  it('CREATE TABLE 안의 테이블 수준 FK도 같은 규칙을 따른다', () => {
    const r = parseDdl(`
      CREATE TABLE ORD (
        MBR_NO bigint,
        CONSTRAINT FK1 FOREIGN KEY (MBR_NO) REFERENCES MBR ON DELETE SET NULL
      );`)
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: 'FK1',
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: [],
    })
  })

  it('컬럼 목록이 있으면 꼬리 절이 있어도 정상이다(대조군)', () => {
    const r = parseDdl('ALTER TABLE ORD ADD CONSTRAINT FK1 FOREIGN KEY (MBR_NO) REFERENCES MBR (MBR_NO) ON DELETE CASCADE;')
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: 'FK1',
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: ['MBR_NO'],
    })
  })

  it('스키마 접두사가 붙은 부모도 마지막 조각만 남긴다(대조군)', () => {
    const r = parseDdl('ALTER TABLE ORD ADD CONSTRAINT FK1 FOREIGN KEY (MBR_NO) REFERENCES "public"."MBR" (MBR_NO);')
    expect(r.constraints[0]).toMatchObject({ refTable: 'MBR', refColumns: ['MBR_NO'] })
  })
})

describe('parseDdl — 컬럼 인라인 제약', () => {
  it('참조 컬럼 목록을 생략한 인라인 REFERENCES를 FK로 잡는다', () => {
    const r = parseDdl('CREATE TABLE ORD (MBR_NO bigint REFERENCES MBR);')
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: null,
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: [],
    })
  })

  it('인라인 REFERENCES의 꼬리 절(ON DELETE 등)이 부모 이름에 섞이지 않는다', () => {
    const r = parseDdl('CREATE TABLE ORD (MBR_NO bigint REFERENCES MBR ON DELETE CASCADE);')
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: null,
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: [],
    })
  })

  it('인라인 CONSTRAINT 이름을 FK 제약명으로 쓴다', () => {
    const r = parseDdl('CREATE TABLE ORD (MBR_NO bigint CONSTRAINT FK_ORD_MBR REFERENCES MBR);')
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: 'FK_ORD_MBR',
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: [],
    })
  })

  it('이름 없는 컬럼 수준 UNIQUE를 UNIQUE 제약으로 잡는다', () => {
    const r = parseDdl('CREATE TABLE MBR (EMAIL text NOT NULL UNIQUE);')
    expect(r.constraints).toContainEqual({
      kind: 'unique', table: 'MBR', name: null, columns: ['EMAIL'],
    })
  })

  it('인라인 CONSTRAINT 이름을 UNIQUE 제약명으로 쓴다', () => {
    const r = parseDdl('CREATE TABLE MBR (EMAIL text NOT NULL CONSTRAINT UX_MBR_EMAIL UNIQUE);')
    expect(r.constraints).toContainEqual({
      kind: 'unique', table: 'MBR', name: 'UX_MBR_EMAIL', columns: ['EMAIL'],
    })
  })

  it('사용자 DDL 형태(여러 줄 constraint … references … on delete cascade)를 그대로 읽는다', () => {
    const r = parseDdl(`
      create table members
      (
          id         uuid                                   not null
              primary key,
          org_id     uuid                                   not null
              constraint members_org_id_organizations_id_fk
                  references organizations
                  on delete cascade,
          user_id    uuid                                   not null
              constraint members_user_id_users_id_fk
                  references users
                  on delete cascade,
          created_at timestamp with time zone default now() not null
      );`)
    expect(r.tables[0]!.columns.map((c) => c.name)).toEqual(['id', 'org_id', 'user_id', 'created_at'])
    expect(r.constraints).toContainEqual({ kind: 'pk', table: 'members', columns: ['id'] })
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'members', name: 'members_org_id_organizations_id_fk',
      columns: ['org_id'], refTable: 'organizations', refColumns: [],
    })
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'members', name: 'members_user_id_users_id_fk',
      columns: ['user_id'], refTable: 'users', refColumns: [],
    })
  })

  it('여러 줄 인라인 UNIQUE도 제약명을 살려 잡는다', () => {
    const r = parseDdl(`
      create table users
      (
          id    uuid not null
              primary key,
          email text not null
              constraint users_email_unique
                  unique
      );`)
    expect(r.constraints).toContainEqual({
      kind: 'unique', table: 'users', name: 'users_email_unique', columns: ['email'],
    })
  })

  it('REFERENCES 뒤의 다른 괄호를 참조 컬럼 목록으로 오인하지 않는다', () => {
    const check = parseDdl('CREATE TABLE ORD (QTY int REFERENCES MBR CHECK (QTY > 0));')
    expect(check.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: null,
      columns: ['QTY'], refTable: 'MBR', refColumns: [],
    })

    const def = parseDdl('CREATE TABLE ORD (REG_DT timestamp REFERENCES MBR DEFAULT now());')
    expect(def.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: null,
      columns: ['REG_DT'], refTable: 'MBR', refColumns: [],
    })
  })

  it('문자열 리터럴 안의 UNIQUE·REFERENCES가 가짜 제약을 만들지 않는다', () => {
    const r = parseDdl("CREATE TABLE A (NOTE varchar(50) DEFAULT 'unique key 재발급 references MBR');")
    expect(r.constraints).toEqual([])
    expect(r.tables[0]!.columns[0]!.defaultValue).toBe("'unique key 재발급 references MBR'")
  })

  it('컬럼 이름이 "unique"여도 유니크 제약으로 오인하지 않는다', () => {
    const r = parseDdl('CREATE TABLE model_indexes (id uuid not null primary key, "unique" boolean not null);')
    expect(r.tables[0]!.columns.map((c) => c.name)).toEqual(['id', 'unique'])
    expect(r.constraints).toEqual([{ kind: 'pk', table: 'model_indexes', columns: ['id'] }])
  })

  it('따옴표 식별자 안의 UNIQUE도 제약으로 오인하지 않는다', () => {
    const r = parseDdl('CREATE TABLE ORD (MBR_NO bigint REFERENCES "unique" (ID));')
    expect(r.constraints).toEqual([{
      kind: 'fk', table: 'ORD', name: null,
      columns: ['MBR_NO'], refTable: 'unique', refColumns: ['ID'],
    }])
  })

  it('테이블 수준 UNIQUE (…)를 컬럼 인라인으로 두 번 세지 않는다', () => {
    const r = parseDdl('CREATE TABLE ORD (A int, B int, CONSTRAINT UX_ORD UNIQUE (A, B));')
    expect(r.constraints.filter((c) => c.kind === 'unique')).toEqual([
      { kind: 'unique', table: 'ORD', name: 'UX_ORD', columns: ['A', 'B'] },
    ])
  })

  // 마스킹본과 원본은 인덱스를 공유한다 — 마스킹이 길이를 바꾸면 그 뒤의 제약명이 통째로
  // 어긋난다. 서로게이트 페어(코드 유닛 2개)를 문자 단위로 순회하면 실제로 그렇게 된다.
  it('괄호 안 마스킹이 서로게이트 페어에서도 길이를 보존한다', () => {
    const r = parseDdl('CREATE TABLE A (COL int CHECK (\u{2000B} > 0) CONSTRAINT UX_A UNIQUE);')
    expect(r.constraints).toContainEqual({
      kind: 'unique', table: 'A', name: 'UX_A', columns: ['COL'],
    })
  })

  // 같은 계약의 다른 경로 — 인용 안의 이스케이프(닫는 문자 두 번)는 2개를 소비하고 2개를
  // 내야 한다. 하나만 내면 마스킹본이 짧아져 뒤의 제약명이 한 글자씩 잘린다(UX_A → UX_).
  it('인용 이스케이프에서도 마스킹이 길이를 보존한다', () => {
    const sq = parseDdl("CREATE TABLE C (A varchar(10) DEFAULT 'a''b' CONSTRAINT UX_A UNIQUE);")
    expect(sq.constraints).toContainEqual({ kind: 'unique', table: 'C', name: 'UX_A', columns: ['A'] })
    expect(sq.tables[0]!.columns[0]!.defaultValue).toBe("'a''b'")

    const dq = parseDdl('CREATE TABLE C (A text COLLATE "a""b" CONSTRAINT UX_A UNIQUE);')
    expect(dq.constraints).toContainEqual({ kind: 'unique', table: 'C', name: 'UX_A', columns: ['A'] })

    const brk = parseDdl('CREATE TABLE C (A text COLLATE [a]]b] CONSTRAINT UX_A UNIQUE);')
    expect(brk.constraints).toContainEqual({ kind: 'unique', table: 'C', name: 'UX_A', columns: ['A'] })

    const btk = parseDdl('CREATE TABLE C (A text COLLATE `a``b` CONSTRAINT UX_A UNIQUE);')
    expect(btk.constraints).toContainEqual({ kind: 'unique', table: 'C', name: 'UX_A', columns: ['A'] })
  })

  it('DEFAULT 값이 뒤따르는 CONSTRAINT 이름을 삼키지 않는다', () => {
    const uq = parseDdl("CREATE TABLE C (A varchar(10) DEFAULT 'x' CONSTRAINT UX1 UNIQUE);")
    expect(uq.tables[0]!.columns[0]!.defaultValue).toBe("'x'")
    expect(uq.constraints).toContainEqual({ kind: 'unique', table: 'C', name: 'UX1', columns: ['A'] })

    const fk = parseDdl('CREATE TABLE C (A int DEFAULT 0 CONSTRAINT FK1 REFERENCES P);')
    expect(fk.tables[0]!.columns[0]!.defaultValue).toBe('0')
    expect(fk.constraints).toContainEqual({
      kind: 'fk', table: 'C', name: 'FK1', columns: ['A'], refTable: 'P', refColumns: [],
    })

    // CHECK 는 건너뛰지만 기본값은 그대로여야 한다.
    const ck = parseDdl('CREATE TABLE C (A int DEFAULT 0 CONSTRAINT CK1 CHECK (A > 0) NOT NULL);')
    expect(ck.tables[0]!.columns[0]!.defaultValue).toBe('0')

    // NOT NULL 이 사이에 끼면 원래부터 정상이었다(대조군).
    const nn = parseDdl("CREATE TABLE C (A varchar(10) DEFAULT 'x' NOT NULL CONSTRAINT UX1 UNIQUE);")
    expect(nn.tables[0]!.columns[0]!.defaultValue).toBe("'x'")
  })

  // 문자열 리터럴과 따옴표 식별자를 각각 따로 훑으면 어느 쪽을 먼저 돌려도 반대편에 구멍이
  // 생긴다. 아래 둘이 그 양쪽이다 — 한 번의 좌→우 스캔으로만 둘 다 통과한다.
  it("따옴표 식별자 안의 아포스트로피가 뒤따르는 제약을 삼키지 않는다", () => {
    const uq = parseDdl(`CREATE TABLE C (A int CONSTRAINT "o'brien" UNIQUE);`)
    expect(uq.constraints).toContainEqual({ kind: 'unique', table: 'C', name: "o'brien", columns: ['A'] })

    const fk = parseDdl(`CREATE TABLE C (A int CONSTRAINT "o'brien" REFERENCES P);`)
    expect(fk.constraints).toContainEqual({
      kind: 'fk', table: 'C', name: "o'brien", columns: ['A'], refTable: 'P', refColumns: [],
    })

    const brk = parseDdl(`CREATE TABLE C (A int CONSTRAINT [o'brien] UNIQUE);`)
    expect(brk.constraints).toContainEqual({ kind: 'unique', table: 'C', name: "o'brien", columns: ['A'] })
  })

  it("따옴표 식별자 안의 아포스트로피가 컬럼 플래그를 뒤집지 않는다", () => {
    const c = parseDdl(`CREATE TABLE C (A int DEFAULT 1 COLLATE "o'brien" NOT NULL);`).tables[0]!.columns[0]!
    expect(c.notNull).toBe(true)
    expect(c.defaultValue).toBe('1')

    const pk = parseDdl(`CREATE TABLE C (A int COLLATE "o'brien" PRIMARY KEY);`)
    expect(pk.tables[0]!.columns[0]!.inlinePk).toBe(true)
    expect(pk.constraints).toContainEqual({ kind: 'pk', table: 'C', columns: ['A'] })
  })

  it('문자열 리터럴 안의 따옴표 문자는 여전히 값의 일부다(대조군)', () => {
    // 반대 방향 구멍 — 식별자를 먼저 훑으면 이 흔한 jsonb 기본값이 깨진다.
    const j = parseDdl(`CREATE TABLE C (A jsonb DEFAULT '{"a": 1}' NOT NULL UNIQUE);`)
    expect(j.tables[0]!.columns[0]!.defaultValue).toBe('\'{"a": 1}\'')
    expect(j.constraints).toContainEqual({ kind: 'unique', table: 'C', name: null, columns: ['A'] })

    const b = parseDdl(`CREATE TABLE C (A varchar(10) DEFAULT 'a[b' NOT NULL UNIQUE);`)
    expect(b.tables[0]!.columns[0]!.defaultValue).toBe("'a[b'")
    expect(b.constraints).toContainEqual({ kind: 'unique', table: 'C', name: null, columns: ['A'] })
  })

  // CONSTRAINT 이름은 **바로 뒤 제약 하나**에만 걸린다(사이에 공백만 있을 때).
  // 이 규칙이 없으면 앞쪽의 무관한 이름이 뒤 제약에 잘못 붙는다.
  it('CONSTRAINT 이름은 바로 뒤 제약 하나에만 걸린다', () => {
    // 사이에 CHECK 가 끼면 CK1 은 REFERENCES 에 붙지 않는다.
    const ck = parseDdl('CREATE TABLE C (A int CONSTRAINT CK1 CHECK (A > 0) REFERENCES P);')
    expect(ck.constraints).toContainEqual({
      kind: 'fk', table: 'C', name: null, columns: ['A'], refTable: 'P', refColumns: [],
    })

    // 이름이 연달아 오면 가장 가까운 것이 이긴다.
    const two = parseDdl('CREATE TABLE C (A int CONSTRAINT X CONSTRAINT Y UNIQUE);')
    expect(two.constraints).toContainEqual({ kind: 'unique', table: 'C', name: 'Y', columns: ['A'] })
    expect(two.constraints).not.toContainEqual({ kind: 'unique', table: 'C', name: 'X', columns: ['A'] })

    // 사이에 NOT NULL 이 끼면 이름이 붙지 않는다.
    const nn = parseDdl('CREATE TABLE C (A int CONSTRAINT NN1 NOT NULL UNIQUE);')
    expect(nn.constraints).toContainEqual({ kind: 'unique', table: 'C', name: null, columns: ['A'] })
  })

  // REFERENCES 해석은 세 경로가 공유하므로 개선도 셋 다에 걸린다. 인라인 경로만
  // 잠그면 테이블 수준·ALTER 쪽 개선을 지워도 아무 테스트가 안 깨진다.
  it('테이블 수준·ALTER FK 도 REFERENCES 뒤 CHECK 괄호를 참조 컬럼으로 읽지 않는다', () => {
    const alt = parseDdl('ALTER TABLE C ADD CONSTRAINT FK1 FOREIGN KEY (A) REFERENCES MBR CHECK (QTY > 0);')
    expect(alt.constraints).toContainEqual({
      kind: 'fk', table: 'C', name: 'FK1', columns: ['A'], refTable: 'MBR', refColumns: [],
    })

    const tbl = parseDdl('CREATE TABLE C (A int, CONSTRAINT FK1 FOREIGN KEY (A) REFERENCES MBR CHECK (QTY > 0));')
    expect(tbl.constraints).toContainEqual({
      kind: 'fk', table: 'C', name: 'FK1', columns: ['A'], refTable: 'MBR', refColumns: [],
    })
  })

  it('참조 컬럼 목록이 있는 인라인 REFERENCES는 그대로다(대조군)', () => {
    const r = parseDdl('CREATE TABLE ORD (MBR_NO bigint NOT NULL REFERENCES "public"."MBR" (MBR_NO) ON DELETE CASCADE);')
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'ORD', name: null,
      columns: ['MBR_NO'], refTable: 'MBR', refColumns: ['MBR_NO'],
    })
  })
})

describe('parseDdl — 비ASCII 식별자', () => {
  it('테이블 수준 제약의 비ASCII 이름을 살린다', () => {
    const uq = parseDdl('CREATE TABLE C (A int, CONSTRAINT 유니크 UNIQUE (A));')
    expect(uq.constraints).toContainEqual({ kind: 'unique', table: 'C', name: '유니크', columns: ['A'] })

    const fk = parseDdl('CREATE TABLE C (A int, CONSTRAINT 외래키 FOREIGN KEY (A) REFERENCES P (I));')
    expect(fk.constraints).toContainEqual({
      kind: 'fk', table: 'C', name: '외래키', columns: ['A'], refTable: 'P', refColumns: ['I'],
    })
  })

  it('ALTER TABLE ADD CONSTRAINT의 비ASCII 이름을 살린다', () => {
    const r = parseDdl('ALTER TABLE C ADD CONSTRAINT 외래키 FOREIGN KEY (A) REFERENCES P (I);')
    expect(r.constraints).toContainEqual({
      kind: 'fk', table: 'C', name: '외래키', columns: ['A'], refTable: 'P', refColumns: ['I'],
    })
  })

  it('비ASCII 컬럼명을 통째로 버리지 않는다', () => {
    const r = parseDdl('CREATE TABLE C (회원번호 int NOT NULL UNIQUE, 이름 varchar(10));')
    expect(r.tables[0]!.columns.map((c) => c.name)).toEqual(['회원번호', '이름'])
    expect(r.tables[0]!.columns[0]!.notNull).toBe(true)
    expect(r.constraints).toContainEqual({ kind: 'unique', table: 'C', name: null, columns: ['회원번호'] })
    expect(r.skipped).toEqual([])
  })

  // 식별자 정규식을 넓히면 컬럼 이름 정규식이 파서의 진입점이라 위험하다 — 테이블 수준
  // 제약이 컬럼으로 먹히면 안 된다. 항목 첫머리 라우팅이 먼저 걸러 준다는 전제를 잠근다.
  it('테이블 수준 제약을 컬럼으로 먹지 않는다', () => {
    const pk = parseDdl('CREATE TABLE C (A int, PRIMARY KEY (A));')
    expect(pk.tables[0]!.columns.map((c) => c.name)).toEqual(['A'])
    expect(pk.constraints).toEqual([{ kind: 'pk', table: 'C', columns: ['A'] }])

    const uq = parseDdl('CREATE TABLE C (A int, UNIQUE (A));')
    expect(uq.tables[0]!.columns.map((c) => c.name)).toEqual(['A'])
    expect(uq.constraints).toEqual([{ kind: 'unique', table: 'C', name: null, columns: ['A'] }])

    const fk = parseDdl('CREATE TABLE C (A int, FOREIGN KEY (A) REFERENCES P (I));')
    expect(fk.tables[0]!.columns.map((c) => c.name)).toEqual(['A'])
    expect(fk.constraints).toEqual([{
      kind: 'fk', table: 'C', name: null, columns: ['A'], refTable: 'P', refColumns: ['I'],
    }])

    const ck = parseDdl('CREATE TABLE C (A int, CHECK (A > 0));')
    expect(ck.tables[0]!.columns.map((c) => c.name)).toEqual(['A'])
    expect(ck.skipped.map((s) => s.keyword)).toEqual(['CHECK'])
  })

  it('비ASCII 이름이 붙은 테이블 수준 CHECK도 컬럼으로 먹지 않는다', () => {
    const r = parseDdl('CREATE TABLE C (A int, CONSTRAINT 체크 CHECK (A > 0));')
    expect(r.tables[0]!.columns.map((c) => c.name)).toEqual(['A'])
    expect(r.constraints).toEqual([])
    expect(r.skipped.map((s) => s.keyword)).toEqual(['CHECK'])
  })
})

describe('머릿말 메타', () => {
  it('머릿말이 있으면 nameMeta 를 싣는다', () => {
    const ddl = [
      '-- erdd:v1 {"TB_MBR_ORD":{"p":"ORD","l":"주문"}}',
      'CREATE TABLE TB_MBR_ORD (ID BIGINT NOT NULL);',
    ].join('\n')
    const parsed = parseDdl(ddl)
    expect(parsed.nameMeta).toEqual({ tables: { TB_MBR_ORD: { p: 'ORD', l: '주문' } }, groups: {} })
    expect(parsed.tables).toHaveLength(1)          // ⚠️ 머릿말이 파싱을 방해하지 않는다
  })

  it('머릿말이 없으면 nameMeta 가 undefined 다', () => {
    expect(parseDdl('CREATE TABLE X (ID BIGINT NOT NULL);').nameMeta).toBeUndefined()
  })
})

/**
 * 부호 없음은 **타입의 일부로 넘긴다**(설계 §4.4-1). 오늘까지는 타입 정규식이 첫 토큰 + 괄호만
 * 집어 `unsigned` 가 `attrs` 로 흘러가 아무도 줍지 않았다.
 *
 * ⚠️ 바뀌는 것은 `attrs` 의 **시작 경계**뿐이다 — `attrsScan = maskQuoted(attrs)` 는 잘린 뒤의
 * 같은 문자열에서 만들어지므로 3.11 의 마스킹 길이 보존 계약은 그대로 성립한다.
 */
describe('parseDdl — 부호 없음 접미', () => {
  it('rawType 이 UNSIGNED 를 물고 오고, attrs 판정이 깨지지 않는다', () => {
    const r = parseDdl('CREATE TABLE ORD (ORD_NO int unsigned NOT NULL AUTO_INCREMENT);')
    const c = r.tables[0]!.columns[0]!
    expect(c.rawType).toBe('int unsigned')
    expect(c.notNull).toBe(true)
    expect(c.autoIncrement).toBe(true)
  })
  it('표시폭과 함께 와도 집는다', () => {
    const r = parseDdl('CREATE TABLE T (A int(10) unsigned NOT NULL, B bigint(20) UNSIGNED);')
    expect(r.tables[0]!.columns.map((c) => c.rawType)).toEqual(['int(10) unsigned', 'bigint(20) UNSIGNED'])
  })
  it('ZEROFILL 도 타입에 함께 집힌다', () => {
    const r = parseDdl('CREATE TABLE T (A int unsigned zerofill NOT NULL);')
    expect(r.tables[0]!.columns[0]!.rawType).toBe('int unsigned zerofill')
    expect(r.tables[0]!.columns[0]!.notNull).toBe(true)
  })
  it('UNSIGNED 가 없으면 rawType 이 그대로다', () => {
    const r = parseDdl('CREATE TABLE T (A int NOT NULL);')
    expect(r.tables[0]!.columns[0]!.rawType).toBe('int')
  })
  it('컬럼 이름이 unsigned 여도 컬럼으로 산다', () => {
    const r = parseDdl('CREATE TABLE T ("unsigned" boolean not null);')
    expect(r.tables[0]!.columns[0]).toMatchObject({ name: 'unsigned', rawType: 'boolean', notNull: true })
  })
})

/**
 * 테이블 꼬리 절은 **파서가 이미 손에 쥐고 있는데 버리고 있었다**(설계 §3.2).
 * 파서는 **해석하지 않는다** — 무엇이 프로젝트 수준 옵션인지 고르는 것은 `ddl-import.ts` 의 일이다.
 */
describe('parseDdl — 테이블 옵션(꼬리 절)', () => {
  it('코멘트를 걷어낸 나머지를 공백 정규화해 담는다', () => {
    const r = parseDdl(
      "CREATE TABLE ORD (A INT)\n  ENGINE=InnoDB   AUTO_INCREMENT=3\n  DEFAULT CHARSET=utf8mb4 COMMENT='주문';",
    )
    // AUTO_INCREMENT 는 여기 그대로 있다 — 거르는 것은 다음 층의 일이다.
    expect(r.tables[0]!.options).toBe('ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4')
    expect(r.comments).toContainEqual({ table: 'ORD', column: null, text: '주문' })
  })
  it('COMMENT 가 앞에 와도 뒤의 옵션이 남는다', () => {
    const r = parseDdl("CREATE TABLE T (A INT) COMMENT='설명' ENGINE=MyISAM;")
    expect(r.tables[0]!.options).toBe('ENGINE=MyISAM')
  })
  it('꼬리가 없으면 필드를 두지 않는다', () => {
    const r = parseDdl('CREATE TABLE T (A INT);')
    expect(r.tables[0]!.options).toBeUndefined()
    expect('options' in r.tables[0]!).toBe(false)
  })
  it('꼬리가 코멘트뿐이면 필드를 두지 않는다', () => {
    const r = parseDdl("CREATE TABLE T (A INT) COMMENT='설명';")
    expect(r.tables[0]!.options).toBeUndefined()
  })
  it('COLLATE 도 그대로 담는다', () => {
    const r = parseDdl(
      'CREATE TABLE T (A INT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
    )
    expect(r.tables[0]!.options).toBe('ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci')
  })
})
