import { describe, expect, it } from 'vitest'
import { generateDdl, ddlWarnings } from './ddl.js'
import { createEmptyModel, type ProjectModel, type Table, type Column } from './model.js'
import { buildSampleModel } from './testing/fixtures.js'

function tbl(id: string, physicalName: string, over: Partial<Table> = {}): Table {
  return { id, logicalName: physicalName, physicalName, comment: null, groupId: null,
    position: { x: 0, y: 0 }, groupPosition: null, custom: {}, ...over }
}
function col(id: string, tableId: string, physicalName: string, type: string, over: Partial<Column> = {}): Column {
  return { id, tableId, logicalName: physicalName, physicalName, type, isPk: false,
    autoIncrement: false, nullable: true, defaultValue: null, order: 0, comment: null,
    domainId: null, custom: {}, ...over }
}

function usersModel(): ProjectModel {
  const m = createEmptyModel()
  m.tables['t'] = tbl('t', 'USERS')
  m.columns['c1'] = col('c1', 't', 'ID', 'BIGINT', { isPk: true, nullable: false, autoIncrement: true, order: 0 })
  m.columns['c2'] = col('c2', 't', 'NAME', 'VARCHAR(100)', { nullable: false, order: 1 })
  m.columns['c3'] = col('c3', 't', 'STATUS', 'CHAR(1)', { defaultValue: "'A'", order: 2 })
  return m
}

describe('generateDdl — CREATE TABLE', () => {
  it('PostgreSQL', () => {
    expect(generateDdl(usersModel(), 'postgresql')).toBe(
`CREATE TABLE USERS (
  ID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NAME varchar(100) NOT NULL,
  STATUS char(1) DEFAULT 'A',
  PRIMARY KEY (ID)
);`)
  })
  it('MySQL 자동증가·타입', () => {
    const ddl = generateDdl(usersModel(), 'mysql')
    expect(ddl).toContain('ID BIGINT AUTO_INCREMENT NOT NULL')
    expect(ddl).toContain('NAME VARCHAR(100) NOT NULL')
    expect(ddl).toContain('PRIMARY KEY (ID)')
  })
  it('Oracle 타입 변환', () => {
    const ddl = generateDdl(usersModel(), 'oracle')
    expect(ddl).toContain('ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL')
    expect(ddl).toContain('NAME VARCHAR2(100) NOT NULL')
  })
  it('범위: 선택 테이블만', () => {
    const m = usersModel()
    m.tables['t2'] = tbl('t2', 'LOGS')
    m.columns['x'] = col('x', 't2', 'MSG', 'TEXT', { order: 0 })
    const ddl = generateDdl(m, 'postgresql', { kind: 'tables', tableIds: ['t2'] })
    expect(ddl).toContain('CREATE TABLE LOGS')
    expect(ddl).not.toContain('CREATE TABLE USERS')
  })
  it('미지 타입은 원문 유지', () => {
    const m = createEmptyModel()
    m.tables['t'] = tbl('t', 'GEO')
    m.columns['c'] = col('c', 't', 'SHAPE', 'geometry', { order: 0 })
    expect(generateDdl(m, 'postgresql')).toContain('SHAPE geometry')
  })
  it('컬럼이 없는 테이블은 CREATE 하지 않고 경고로 알린다', () => {
    const m = usersModel()
    m.tables['empty'] = tbl('empty', 'EMPTY_TBL')
    const sql = generateDdl(m, 'postgresql')
    expect(sql).not.toContain('CREATE TABLE EMPTY_TBL')
    expect(sql).not.toContain('(\n\n)')
    expect(ddlWarnings(m, 'postgresql')).toEqual(
      expect.arrayContaining([expect.stringContaining('EMPTY_TBL')]),
    )
  })

  it('도메인 컬럼은 방언 타입·CHECK·기본값을 반영한다', () => {
    const m = createEmptyModel()
    m.tables['t'] = tbl('t', 'FLAGS')
    m.domains['d'] = { id: 'd', name: '여부', category: null, logicalType: 'CHAR(1)',
      dialectTypes: { postgresql: null, mysql: null, oracle: null, mssql: null },
      defaultValue: "'N'", allowedValues: ['Y', 'N'], description: null, origin: null }
    m.columns['c'] = col('c', 't', 'USE_YN', 'INT', { order: 0, domainId: 'd' }) // type INT은 무시(잠금)
    const pg = generateDdl(m, 'postgresql')
    expect(pg).toContain('USE_YN char(1)')          // 도메인 논리타입 변환
    expect(pg).toContain("DEFAULT 'N'")              // 도메인 기본값
    expect(pg).toContain("CHECK (USE_YN IN ('Y', 'N'))") // 허용값
  })

  it('예약어 물리명을 방언별로 인용한다', () => {
    const m = createEmptyModel()
    m.tables['t'] = tbl('t', 'ORDER', { comment: '주문' })
    m.columns['c'] = col('c', 't', 'USER', 'BIGINT', { order: 0, comment: '사용자' })
    // PostgreSQL
    const pg = generateDdl(m, 'postgresql')
    expect(pg).toContain('CREATE TABLE "ORDER"')
    expect(pg).toContain('"USER"')
    expect(pg).toContain('COMMENT ON TABLE "ORDER" IS')
    // MySQL
    expect(generateDdl(m, 'mysql')).toContain('CREATE TABLE `ORDER`')
    // MSSQL 코멘트문(sp_addextendedproperty)의 이름은 N'...' 문자열 리터럴이므로 대괄호로 인용하지 않는다
    const ms = generateDdl(m, 'mssql')
    expect(ms).toContain('CREATE TABLE [ORDER]')
    expect(ms).toContain("@level1name=N'ORDER'")
    expect(ms).not.toContain("@level1name=N'[ORDER]'")
    // 컬럼레벨 코멘트 이름도 리터럴이라 대괄호로 인용하지 않는다
    expect(ms).toContain("@level2name=N'USER'")
    expect(ms).not.toContain("@level2name=N'[USER]'")
  })
})

// 관계·인덱스·코멘트가 있는 모델
function relModel(): ProjectModel {
  const m = createEmptyModel()
  m.tables['p'] = tbl('p', 'USERS', { logicalName: '회원', comment: '회원 마스터' })
  m.tables['c'] = tbl('c', 'ORDERS', { logicalName: '주문' })
  m.columns['pk'] = col('pk', 'p', 'ID', 'BIGINT', { isPk: true, nullable: false, order: 0, logicalName: '아이디' })
  m.columns['fk'] = col('fk', 'c', 'USER_ID', 'BIGINT', { nullable: false, order: 0 })
  m.columns['co'] = col('co', 'c', 'ID', 'BIGINT', { isPk: true, nullable: false, order: 1 })
  m.relationships['r'] = { id: 'r', parentTableId: 'p', childTableId: 'c',
    columnMappings: [{ childColumnId: 'fk', parentColumnId: 'pk' }],
    cardinality: '1:N', identifying: false, name: null }
  m.indexes['ix'] = { id: 'ix', tableId: 'c', name: 'IX_ORDERS_USER', unique: false,
    columns: [{ columnId: 'fk', direction: 'asc' }] }
  return m
}

describe('generateDdl — FK·인덱스·코멘트', () => {
  it('PostgreSQL FK·인덱스·코멘트', () => {
    const ddl = generateDdl(relModel(), 'postgresql')
    expect(ddl).toContain('ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID);')
    expect(ddl).toContain('CREATE INDEX IX_ORDERS_USER ON ORDERS (USER_ID ASC);')
    expect(ddl).toContain("COMMENT ON TABLE USERS IS '회원 - 회원 마스터';")
    expect(ddl).toContain("COMMENT ON COLUMN USERS.ID IS '아이디';")
  })
  it('1:1 관계는 UNIQUE 제약 포함', () => {
    const m = relModel()
    m.relationships['r']!.cardinality = '1:1'
    const ddl = generateDdl(m, 'postgresql')
    expect(ddl).toContain('UNIQUE (USER_ID)')
  })
  it('MySQL 인라인 코멘트', () => {
    const ddl = generateDdl(relModel(), 'mysql')
    expect(ddl).toContain("COMMENT '회원 - 회원 마스터'") // 테이블
    expect(ddl).not.toContain('COMMENT ON')
  })
  it('MSSQL 확장 속성', () => {
    const ddl = generateDdl(relModel(), 'mssql')
    expect(ddl).toContain('sp_addextendedproperty')
  })
  it('FK는 양 끝이 선택 범위에 있을 때만', () => {
    const ddl = generateDdl(relModel(), 'postgresql', { kind: 'tables', tableIds: ['c'] })
    expect(ddl).not.toContain('ADD CONSTRAINT FK_') // 부모 USERS 미포함
  })

  it('같은 테이블 쌍의 무명 관계 2개는 제약명이 충돌하지 않는다', () => {
    const m = relModel()
    // 두 번째 자식 FK 컬럼 + 두 번째 무명 관계(같은 c→p 쌍).
    m.columns['fk2'] = col('fk2', 'c', 'USER_ID2', 'BIGINT', { nullable: false, order: 2 })
    m.relationships['r2'] = { id: 'r2', parentTableId: 'p', childTableId: 'c',
      columnMappings: [{ childColumnId: 'fk2', parentColumnId: 'pk' }],
      cardinality: '1:N', identifying: false, name: null }
    const ddl = generateDdl(m, 'postgresql')
    expect(ddl).toContain('ADD CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USER_ID)')
    expect(ddl).toContain('ADD CONSTRAINT FK_ORDERS_USERS_2 FOREIGN KEY (USER_ID2)')
  })
})

describe('빈 물리명', () => {
  it('물리명이 빈 테이블은 DDL에서 빠지고 경고가 나온다', () => {
    const m = buildSampleModel()
    m.tables['t1']!.physicalName = ''
    const sql = generateDdl(m, 'postgresql')
    expect(sql).not.toContain('CREATE TABLE ""')
    // t1의 유일한 컬럼은 GRD_CD인데, t2의 FK 컬럼(c4)도 물리명이 같은 GRD_CD라서
    // 'GRD_CD' 부분 문자열 검사로는 t1이 빠졌는지 구분할 수 없다(정정: 원래 브리프는
    // not.toContain('GRD_CD')였으나 buildSampleModel 픽스처와 충돌해 t2가 정상 포함돼도
    // 항상 실패한다). t1의 CREATE TABLE 블록 자체가 없는지로 대체 검증한다.
    expect(sql).not.toContain('CREATE TABLE MBR_GRD (')
    expect(sql).toContain('MBR')                  // t2는 그대로 나온다
    const warns = ddlWarnings(m, 'postgresql')
    expect(warns.some((w) => w.includes('물리명'))).toBe(true)
  })

  it('물리명이 빈 컬럼이 있으면 그 테이블이 통째로 빠진다', () => {
    const m = buildSampleModel()
    m.columns['c3']!.physicalName = ''            // c3는 t2의 컬럼
    const sql = generateDdl(m, 'postgresql')
    // 정정: MBR은 예약어도 아니고 SAFE 패턴(영문자/숫자/밑줄)이라 quoteIdentifier가
    // 인용하지 않는다(identifier.ts:34) — 원래 브리프의 'CREATE TABLE "MBR"'(따옴표 포함)는
    // postgresql 출력에 결코 나타나지 않아 구현 여부와 무관하게 항상 통과하는 무의미한 단언이었다
    // (되돌리기 실증으로 확인: 구현 삭제 상태에서도 이 단언은 통과했다). 실제 출력 형식(따옴표 없음)에
    // 맞춰 구분력 있는 단언으로 정정한다.
    expect(sql).not.toContain('CREATE TABLE MBR (')
    expect(sql).toContain('MBR_GRD')              // t1은 그대로
    const warns = ddlWarnings(m, 'postgresql')
    expect(warns.some((w) => w.includes('물리명'))).toBe(true)
  })

  it('빠진 테이블을 참조하는 FK도 함께 빠진다', () => {
    const m = buildSampleModel()
    m.tables['t1']!.physicalName = ''             // r1의 부모
    const sql = generateDdl(m, 'postgresql')
    expect(sql).not.toContain('FOREIGN KEY')
  })

  // ⚠️ 없으면 "항상 제외한다"는 구현도 위 셋을 통과한다.
  it('물리명이 모두 차 있으면 아무것도 빠지지 않는다', () => {
    const m = buildSampleModel()
    const sql = generateDdl(m, 'postgresql')
    expect(sql).toContain('MBR_GRD')
    expect(sql).toContain('FOREIGN KEY')
    const warns = ddlWarnings(m, 'postgresql')
    expect(warns.some((w) => w.includes('물리명'))).toBe(false)
  })
})
