import { describe, expect, it } from 'vitest'
import { generateDdl } from './ddl.js'
import { createEmptyModel, type ProjectModel, type Table, type Column } from './model.js'

function tbl(id: string, physicalName: string, over: Partial<Table> = {}): Table {
  return { id, logicalName: physicalName, physicalName, comment: null, groupId: null,
    position: { x: 0, y: 0 }, groupPosition: null, ...over }
}
function col(id: string, tableId: string, physicalName: string, type: string, over: Partial<Column> = {}): Column {
  return { id, tableId, logicalName: physicalName, physicalName, type, isPk: false,
    autoIncrement: false, nullable: true, defaultValue: null, order: 0, comment: null, ...over }
}

function usersModel(): ProjectModel {
  const m = createEmptyModel()
  m.tables['t'] = tbl('t', 'USERS')
  m.columns['c1'] = col('c1', 't', 'ID', 'BIGINT', { isPk: true, nullable: false, autoIncrement: true, order: 0 })
  m.columns['c2'] = col('c2', 't', 'NAME', 'VARCHAR(100)', { nullable: false, order: 1 })
  m.columns['c3'] = col('c3', 't', 'STATUS', 'CHAR(1)', { defaultValue: "'A'", order: 2 })
  return m
}

describe('generateDdl — CREATE TABLE', () => {
  it('PostgreSQL', () => {
    expect(generateDdl(usersModel(), 'postgresql')).toBe(
`CREATE TABLE USERS (
  ID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NAME varchar(100) NOT NULL,
  STATUS char(1) DEFAULT 'A',
  PRIMARY KEY (ID)
);`)
  })
  it('MySQL 자동증가·타입', () => {
    const ddl = generateDdl(usersModel(), 'mysql')
    expect(ddl).toContain('ID BIGINT AUTO_INCREMENT NOT NULL')
    expect(ddl).toContain('NAME VARCHAR(100) NOT NULL')
    expect(ddl).toContain('PRIMARY KEY (ID)')
  })
  it('Oracle 타입 변환', () => {
    const ddl = generateDdl(usersModel(), 'oracle')
    expect(ddl).toContain('ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL')
    expect(ddl).toContain('NAME VARCHAR2(100) NOT NULL')
  })
  it('범위: 선택 테이블만', () => {
    const m = usersModel()
    m.tables['t2'] = tbl('t2', 'LOGS')
    m.columns['x'] = col('x', 't2', 'MSG', 'TEXT', { order: 0 })
    const ddl = generateDdl(m, 'postgresql', { kind: 'tables', tableIds: ['t2'] })
    expect(ddl).toContain('CREATE TABLE LOGS')
    expect(ddl).not.toContain('CREATE TABLE USERS')
  })
  it('미지 타입은 원문 유지', () => {
    const m = createEmptyModel()
    m.tables['t'] = tbl('t', 'GEO')
    m.columns['c'] = col('c', 't', 'SHAPE', 'geometry', { order: 0 })
    expect(generateDdl(m, 'postgresql')).toContain('SHAPE geometry')
  })
  it('예약어 물리명을 방언별로 인용한다', () => {
    const m = createEmptyModel()
    m.tables['t'] = tbl('t', 'ORDER', { comment: '주문' })
    m.columns['c'] = col('c', 't', 'USER', 'BIGINT', { order: 0, comment: '사용자' })
    // PostgreSQL
    const pg = generateDdl(m, 'postgresql')
    expect(pg).toContain('CREATE TABLE "ORDER"')
    expect(pg).toContain('"USER"')
    expect(pg).toContain('COMMENT ON TABLE "ORDER" IS')
    // MySQL
    expect(generateDdl(m, 'mysql')).toContain('CREATE TABLE `ORDER`')
    // MSSQL 코멘트문(sp_addextendedproperty)의 이름은 N'...' 문자열 리터럴이므로 대괄호로 인용하지 않는다
    const ms = generateDdl(m, 'mssql')
    expect(ms).toContain('CREATE TABLE [ORDER]')
    expect(ms).toContain("@level1name=N'ORDER'")
    expect(ms).not.toContain("@level1name=N'[ORDER]'")
  })
})

// 관계·인덱스·코멘트가 있는 모델
function relModel(): ProjectModel {
  const m = createEmptyModel()
  m.tables['p'] = tbl('p', 'USERS', { logicalName: '회원', comment: '회원 마스터' })
  m.tables['c'] = tbl('c', 'ORDERS', { logicalName: '주문' })
  m.columns['pk'] = col('pk', 'p', 'ID', 'BIGINT', { isPk: true, nullable: false, order: 0, logicalName: '아이디' })
  m.columns['fk'] = col('fk', 'c', 'USER_ID', 'BIGINT', { nullable: false, order: 0 })
  m.columns['co'] = col('co', 'c', 'ID', 'BIGINT', { isPk: true, nullable: false, order: 1 })
  m.relationships['r'] = { id: 'r', parentTableId: 'p', childTableId: 'c',
    columnMappings: [{ childColumnId: 'fk', parentColumnId: 'pk' }],
    cardinality: '1:N', identifying: false, name: null }
  m.indexes['ix'] = { id: 'ix', tableId: 'c', name: 'IX_ORDERS_USER', unique: false,
    columns: [{ columnId: 'fk', direction: 'asc' }] }
  return m
}

describe('generateDdl — FK·인덱스·코멘트', () => {
  it('PostgreSQL FK·인덱스·코멘트', () => {
    const ddl = generateDdl(relModel(), 'postgresql')
    expect(ddl).toContain('ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID);')
    expect(ddl).toContain('CREATE INDEX IX_ORDERS_USER ON ORDERS (USER_ID ASC);')
    expect(ddl).toContain("COMMENT ON TABLE USERS IS '회원 - 회원 마스터';")
    expect(ddl).toContain("COMMENT ON COLUMN USERS.ID IS '아이디';")
  })
  it('1:1 관계는 UNIQUE 제약 포함', () => {
    const m = relModel()
    m.relationships['r']!.cardinality = '1:1'
    const ddl = generateDdl(m, 'postgresql')
    expect(ddl).toContain('UNIQUE (USER_ID)')
  })
  it('MySQL 인라인 코멘트', () => {
    const ddl = generateDdl(relModel(), 'mysql')
    expect(ddl).toContain("COMMENT '회원 - 회원 마스터'") // 테이블
    expect(ddl).not.toContain('COMMENT ON')
  })
  it('MSSQL 확장 속성', () => {
    const ddl = generateDdl(relModel(), 'mssql')
    expect(ddl).toContain('sp_addextendedproperty')
  })
  it('FK는 양 끝이 선택 범위에 있을 때만', () => {
    const ddl = generateDdl(relModel(), 'postgresql', { kind: 'tables', tableIds: ['c'] })
    expect(ddl).not.toContain('ADD CONSTRAINT FK_') // 부모 USERS 미포함
  })

  it('같은 테이블 쌍의 무명 관계 2개는 제약명이 충돌하지 않는다', () => {
    const m = relModel()
    // 두 번째 자식 FK 컬럼 + 두 번째 무명 관계(같은 c→p 쌍).
    m.columns['fk2'] = col('fk2', 'c', 'USER_ID2', 'BIGINT', { nullable: false, order: 2 })
    m.relationships['r2'] = { id: 'r2', parentTableId: 'p', childTableId: 'c',
      columnMappings: [{ childColumnId: 'fk2', parentColumnId: 'pk' }],
      cardinality: '1:N', identifying: false, name: null }
    const ddl = generateDdl(m, 'postgresql')
    expect(ddl).toContain('ADD CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USER_ID)')
    expect(ddl).toContain('ADD CONSTRAINT FK_ORDERS_USERS_2 FOREIGN KEY (USER_ID2)')
  })
})
