import type { Column, ProjectModel, Table } from './model.js'
import { resolveColumnType, type Dialect } from './dialect.js'
import { parseLogicalType } from './logical-type.js'

export type DdlScope =
  | { kind: 'all' }
  | { kind: 'group'; groupId: string }
  | { kind: 'tables'; tableIds: string[] }

const INT_KINDS = new Set(['SMALLINT', 'INT', 'BIGINT'])

function isIntegerType(type: string): boolean {
  const p = parseLogicalType(type)
  return p.ok && INT_KINDS.has(p.type.kind)
}

function autoIncrementToken(dialect: Dialect): string {
  switch (dialect) {
    case 'postgresql':
    case 'oracle':
      return 'GENERATED BY DEFAULT AS IDENTITY'
    case 'mysql':
      return 'AUTO_INCREMENT'
    case 'mssql':
      return 'IDENTITY(1,1)'
  }
}

function selectTables(model: ProjectModel, scope: DdlScope): Table[] {
  const all = Object.values(model.tables)
  let picked: Table[]
  if (scope.kind === 'all') picked = all
  else if (scope.kind === 'group') picked = all.filter((t) => t.groupId === scope.groupId)
  else {
    const ids = new Set(scope.tableIds)
    picked = all.filter((t) => ids.has(t.id))
  }
  return picked.sort((a, b) => a.physicalName.localeCompare(b.physicalName))
}

function tableColumns(model: ProjectModel, tableId: string): Column[] {
  return Object.values(model.columns).filter((c) => c.tableId === tableId).sort((a, b) => a.order - b.order)
}

function columnLine(col: Column, dialect: Dialect): string {
  const parts = [col.physicalName, resolveColumnType(col.type, dialect).sql]
  const auto = col.autoIncrement && col.isPk && isIntegerType(col.type)
  if (auto) parts.push(autoIncrementToken(dialect))
  if (!col.nullable) parts.push('NOT NULL')
  if (!auto && col.defaultValue !== null && col.defaultValue !== '') parts.push(`DEFAULT ${col.defaultValue}`)
  return `  ${parts.join(' ')}`
}

export function generateDdl(model: ProjectModel, dialect: Dialect, scope: DdlScope = { kind: 'all' }): string {
  const tables = selectTables(model, scope)
  const blocks = tables.map((table) => {
    const cols = tableColumns(model, table.id)
    const lines = cols.map((c) => columnLine(c, dialect))
    const pks = cols.filter((c) => c.isPk)
    if (pks.length > 0) lines.push(`  PRIMARY KEY (${pks.map((c) => c.physicalName).join(', ')})`)
    return `CREATE TABLE ${table.physicalName} (\n${lines.join(',\n')}\n);`
  })
  return blocks.join('\n\n')
}
