import { describe, expect, it } from 'vitest'
import { generateDdl } from './ddl.js'
import { createEmptyModel, type ProjectModel, type Table, type Column } from './model.js'

function tbl(id: string, physicalName: string, over: Partial<Table> = {}): Table {
  return { id, logicalName: physicalName, physicalName, comment: null, groupId: null,
    position: { x: 0, y: 0 }, groupPosition: null, ...over }
}
function col(id: string, tableId: string, physicalName: string, type: string, over: Partial<Column> = {}): Column {
  return { id, tableId, logicalName: physicalName, physicalName, type, isPk: false,
    autoIncrement: false, nullable: true, defaultValue: null, order: 0, comment: null, ...over }
}

function usersModel(): ProjectModel {
  const m = createEmptyModel()
  m.tables['t'] = tbl('t', 'USERS')
  m.columns['c1'] = col('c1', 't', 'ID', 'BIGINT', { isPk: true, nullable: false, autoIncrement: true, order: 0 })
  m.columns['c2'] = col('c2', 't', 'NAME', 'VARCHAR(100)', { nullable: false, order: 1 })
  m.columns['c3'] = col('c3', 't', 'STATUS', 'CHAR(1)', { defaultValue: "'A'", order: 2 })
  return m
}

describe('generateDdl — CREATE TABLE', () => {
  it('PostgreSQL', () => {
    expect(generateDdl(usersModel(), 'postgresql')).toBe(
`CREATE TABLE USERS (
  ID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NAME varchar(100) NOT NULL,
  STATUS char(1) DEFAULT 'A',
  PRIMARY KEY (ID)
);`)
  })
  it('MySQL 자동증가·타입', () => {
    const ddl = generateDdl(usersModel(), 'mysql')
    expect(ddl).toContain('ID BIGINT AUTO_INCREMENT NOT NULL')
    expect(ddl).toContain('NAME VARCHAR(100) NOT NULL')
    expect(ddl).toContain('PRIMARY KEY (ID)')
  })
  it('Oracle 타입 변환', () => {
    const ddl = generateDdl(usersModel(), 'oracle')
    expect(ddl).toContain('ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL')
    expect(ddl).toContain('NAME VARCHAR2(100) NOT NULL')
  })
  it('범위: 선택 테이블만', () => {
    const m = usersModel()
    m.tables['t2'] = tbl('t2', 'LOGS')
    m.columns['x'] = col('x', 't2', 'MSG', 'TEXT', { order: 0 })
    const ddl = generateDdl(m, 'postgresql', { kind: 'tables', tableIds: ['t2'] })
    expect(ddl).toContain('CREATE TABLE LOGS')
    expect(ddl).not.toContain('CREATE TABLE USERS')
  })
  it('미지 타입은 원문 유지', () => {
    const m = createEmptyModel()
    m.tables['t'] = tbl('t', 'GEO')
    m.columns['c'] = col('c', 't', 'SHAPE', 'geometry', { order: 0 })
    expect(generateDdl(m, 'postgresql')).toContain('SHAPE geometry')
  })
})
