import type { Column, ProjectModel, Relationship, Table } from './model.js'
import { resolveColumnType, type Dialect } from './dialect.js'
import { isUnsignedCapable, parseLogicalType } from './logical-type.js'
import type { TableOptions } from './table-options.js'
import { quoteIdentifier } from './identifier.js'
import { resolveColumn } from './domain-resolve.js'
import { composeTableLogicalName, composeTablePhysicalName } from './name-template.js'
import type { NamingRules } from './naming.js'
import { buildNameMeta, serializeNameMeta } from './name-meta.js'

export type DdlScope =
  | { kind: 'all' }
  | { kind: 'group'; groupId: string }
  | { kind: 'tables'; tableIds: string[] }

/** 내보내기 범위. DDL 전용이 아니라 Excel 산출물도 같은 범위 개념을 쓴다. */
export type ExportScope = DdlScope

const INT_KINDS = new Set(['SMALLINT', 'INT', 'BIGINT'])

function isIntegerType(type: string): boolean {
  const p = parseLogicalType(type)
  return p.ok && INT_KINDS.has(p.type.kind)
}

function autoIncrementToken(dialect: Dialect): string {
  switch (dialect) {
    case 'postgresql':
    case 'oracle':
      return 'GENERATED BY DEFAULT AS IDENTITY'
    case 'mysql':
      return 'AUTO_INCREMENT'
    case 'mssql':
      return 'IDENTITY(1,1)'
  }
}

export function selectTables(
  model: ProjectModel, scope: DdlScope, rules: NamingRules,
): Table[] {
  const all = Object.values(model.tables)
  let picked: Table[]
  if (scope.kind === 'all') picked = all
  else if (scope.kind === 'group') picked = all.filter((t) => t.groupId === scope.groupId)
  else {
    const ids = new Set(scope.tableIds)
    picked = all.filter((t) => ids.has(t.id))
  }
  // ⚠️ 최종 이름 기준으로 정렬한다 — 그래야 DDL 순서가 실제로 만들어질 테이블 순서와 맞는다.
  const compose = (t: Table) => composeTablePhysicalName(t, model, rules)
  return picked.sort((a, b) => compose(a).localeCompare(compose(b)))
}

export function tableColumns(model: ProjectModel, tableId: string): Column[] {
  return Object.values(model.columns).filter((c) => c.tableId === tableId).sort((a, b) => a.order - b.order)
}

/** logicalName/physicalName/comment로부터 코멘트 텍스트 산출. 논리명==물리명이고 설명이 없으면 생략(null). */
export function commentText(logicalName: string, physicalName: string, comment: string | null): string | null {
  const parts: string[] = []
  if (logicalName && logicalName !== physicalName) parts.push(logicalName)
  else if (logicalName && logicalName === physicalName && comment) parts.push(logicalName)
  if (comment) parts.push(comment)
  if (parts.length === 0) return null
  return parts.join(' - ')
}

const esc = (s: string) => s.replace(/'/g, "''")

function fkBaseName(rel: { name: string | null }, child: string, parent: string): string {
  return rel.name && rel.name.trim() !== '' ? rel.name : `FK_${child}_${parent}`
}

/** 배치 안에서 제약명이 유일하도록 보장한다(충돌 시 _2, _3… 접미). */
function uniqueConstraintName(base: string, used: Set<string>): string {
  if (!used.has(base)) { used.add(base); return base }
  let n = 2
  while (used.has(`${base}_${n}`)) n++
  const name = `${base}_${n}`
  used.add(name)
  return name
}

function needsUnsignedCheck(logicalType: string): boolean {
  const p = parseLogicalType(logicalType)
  return p.ok && isUnsignedCapable(p.type) && p.type.unsigned
}

function columnLine(model: ProjectModel, col: Column, dialect: Dialect): string {
  const r = resolveColumn(col, model, dialect)
  const parts = [quoteIdentifier(col.physicalName, dialect), r.sql]
  const auto = col.autoIncrement && col.isPk && isIntegerType(r.logicalType)
  if (auto) parts.push(autoIncrementToken(dialect))
  if (!col.nullable) parts.push('NOT NULL')
  if (!auto && r.defaultValue !== null && r.defaultValue !== '') parts.push(`DEFAULT ${r.defaultValue}`)
  // CHECK 는 **둘**이 될 수 있다 — 도메인 허용값과 부호 없음.
  if (r.checkValues && r.checkValues.length > 0) {
    const list = r.checkValues.map((v) => `'${esc(v)}'`).join(', ')
    parts.push(`CHECK (${quoteIdentifier(col.physicalName, dialect)} IN (${list}))`)
  }
  // mysql 밖에는 부호 없음 타입이 없으므로 「음수가 될 수 없다」를 CHECK 로 나른다(설계 §4.5).
  // ⚠️ 판정 기준은 **해석된 논리 타입**(`r.logicalType`)이다 — 컬럼 자신의 문자열을 보면
  // 도메인을 지정한 컬럼이 조용히 빠진다(§3.4 다의 함정). 방언별 물리 타입 오버라이드가
  // 있어도 낸다 — 오버라이드는 저장 형태, CHECK 는 값이라 서로 배타적이지 않다.
  if (dialect !== 'mysql' && needsUnsignedCheck(r.logicalType)) {
    parts.push(`CHECK (${quoteIdentifier(col.physicalName, dialect)} >= 0)`)
  }
  if (dialect === 'mysql') {
    const text = commentText(col.logicalName, col.physicalName, col.comment)
    if (text !== null) parts.push(`COMMENT '${esc(text)}'`)
  }
  return `  ${parts.join(' ')}`
}

function createTableBlock(
  model: ProjectModel, table: Table, dialect: Dialect, rules: NamingRules,
  tableOptions?: TableOptions,
): string {
  const tableName = composeTablePhysicalName(table, model, rules)
  const cols = tableColumns(model, table.id)
  const lines = cols.map((c) => columnLine(model, c, dialect))
  const pks = cols.filter((c) => c.isPk)
  if (pks.length > 0) lines.push(`  PRIMARY KEY (${pks.map((c) => quoteIdentifier(c.physicalName, dialect)).join(', ')})`)
  let block = `CREATE TABLE ${quoteIdentifier(tableName, dialect)} (\n${lines.join(',\n')}\n)`
  // ⚠️ **`COMMENT` 앞에 둔다.** 파서의 테이블 코멘트 추출이 꼬리에서 첫 `COMMENT` 키워드를
  // 찾으므로 옵션이 앞이어야 그 스캔이 그대로 맞는다(설계 §5.4). 빈 문자열이면 한 글자도
  // 붙이지 않는다 — 옵션을 안 쓰는 프로젝트의 산출물이 달라지면 안 된다.
  const opts = tableOptions?.[dialect].trim() ?? ''
  if (opts !== '') block += ` ${opts}`
  if (dialect === 'mysql') {
    // 「논리명==물리명이면 생략」 판정은 **양쪽 다 최종 이름**으로 한다(설계 D5).
    const text = commentText(composeTableLogicalName(table, model, rules), tableName, table.comment)
    if (text !== null) block += ` COMMENT '${esc(text)}'`
  }
  return `${block};`
}

/**
 * DDL로 낼 수 있는 테이블인가. 물리명이 비면 식별자를 만들 수 없다.
 * generateDdl의 제외와 ddlWarnings의 경고가 같은 판정을 써야 하므로 여기 하나만 둔다.
 */
export function hasEmptyPhysicalName(
  model: ProjectModel, table: Table, rules: NamingRules,
): boolean {
  // ⚠️ 부분이 비어도 접두가 있으면 유효한 이름이다 — 조합 결과로 판정한다(설계 3.3).
  if (composeTablePhysicalName(table, model, rules).trim() === '') return true
  return tableColumns(model, table.id).some((c) => c.physicalName.trim() === '')
}

/**
 * 경고 문구에 쓸 테이블 라벨. 물리명이 비어 있으면 논리명(없으면 id)으로 폴백한다 —
 * 그렇지 않으면 신규 테이블(물리명 '')의 경고가 ": ..." 형태로 이름 없이 뜬다.
 * ⚠️ 폴백도 **최종 이름**이다(설계 D5) — 화면에 없는 부분을 가리키면 안 된다.
 */
function warningLabel(t: Table, model: ProjectModel, rules: NamingRules): string {
  const name = composeTablePhysicalName(t, model, rules)
  return name.trim() === '' ? (composeTableLogicalName(t, model, rules) || t.id) : name
}

function selectedRelationships(model: ProjectModel, selectedIds: Set<string>): Relationship[] {
  return Object.values(model.relationships).filter(
    (r) => selectedIds.has(r.parentTableId) && selectedIds.has(r.childTableId),
  )
}

function fkStatements(
  model: ProjectModel, selectedIds: Set<string>, dialect: Dialect, rules: NamingRules,
): string[] {
  const compose = (t: Table) => composeTablePhysicalName(t, model, rules)
  const rels = selectedRelationships(model, selectedIds)
  const statements: string[] = []
  const used = new Set<string>() // 원문 기준 유일성 추적, 출력 시 인용
  const q = (s: string) => quoteIdentifier(s, dialect)
  for (const rel of rels) {
    const parent = model.tables[rel.parentTableId]
    const child = model.tables[rel.childTableId]
    if (!parent || !child) continue
    const rawChildCols = rel.columnMappings.map((m) => model.columns[m.childColumnId]?.physicalName ?? '')
    const childCols = rawChildCols.map(q)
    const parentCols = rel.columnMappings.map((m) => q(model.columns[m.parentColumnId]?.physicalName ?? ''))
    const childName = compose(child)
    const parentName = compose(parent)
    const name = uniqueConstraintName(fkBaseName(rel, childName, parentName), used)
    statements.push(
      `ALTER TABLE ${q(childName)} ADD CONSTRAINT ${q(name)} FOREIGN KEY (${childCols.join(', ')}) REFERENCES ${q(parentName)} (${parentCols.join(', ')});`,
    )
    if (rel.cardinality === '1:1') {
      const uqName = uniqueConstraintName(`UQ_${childName}_${rawChildCols.join('_')}`, used)
      statements.push(`ALTER TABLE ${q(childName)} ADD CONSTRAINT ${q(uqName)} UNIQUE (${childCols.join(', ')});`)
    }
  }
  return statements
}

function indexStatements(
  model: ProjectModel, selectedIds: Set<string>, dialect: Dialect, rules: NamingRules,
): string[] {
  const indexes = Object.values(model.indexes).filter((ix) => selectedIds.has(ix.tableId))
  const q = (s: string) => quoteIdentifier(s, dialect)
  return indexes.map((ix) => {
    const table = model.tables[ix.tableId]
    const tableName = table ? composeTablePhysicalName(table, model, rules) : ix.tableId
    const cols = ix.columns
      .map((c) => {
        const col = model.columns[c.columnId]
        const colName = col ? col.physicalName : c.columnId
        return `${q(colName)} ${c.direction.toUpperCase()}`
      })
      .join(', ')
    const uniqueToken = ix.unique ? 'UNIQUE ' : ''
    return `CREATE ${uniqueToken}INDEX ${q(ix.name)} ON ${q(tableName)} (${cols});`
  })
}

function commentStatements(
  model: ProjectModel, tables: Table[], dialect: Dialect, rules: NamingRules,
): string[] {
  const statements: string[] = []
  for (const table of tables) {
    const tableName = composeTablePhysicalName(table, model, rules)
    // 「논리명==물리명이면 생략」 판정은 **양쪽 다 최종 이름**으로 한다(설계 D5).
    const tableText = commentText(composeTableLogicalName(table, model, rules), tableName, table.comment)
    if (tableText !== null) statements.push(tableCommentStatement(dialect, tableName, tableText))
    const cols = tableColumns(model, table.id)
    for (const col of cols) {
      const colText = commentText(col.logicalName, col.physicalName, col.comment)
      if (colText !== null) statements.push(columnCommentStatement(dialect, tableName, col.physicalName, colText))
    }
  }
  return statements
}

function tableCommentStatement(dialect: Dialect, tableName: string, text: string): string {
  switch (dialect) {
    case 'postgresql':
    case 'oracle':
      return `COMMENT ON TABLE ${quoteIdentifier(tableName, dialect)} IS '${esc(text)}';`
    case 'mssql':
      return `EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'${esc(text)}', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'${tableName}';`
    case 'mysql':
      throw new Error('MySQL uses inline comments')
  }
}

function columnCommentStatement(dialect: Dialect, tableName: string, columnName: string, text: string): string {
  switch (dialect) {
    case 'postgresql':
    case 'oracle':
      return `COMMENT ON COLUMN ${quoteIdentifier(tableName, dialect)}.${quoteIdentifier(columnName, dialect)} IS '${esc(text)}';`
    case 'mssql':
      return `EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'${esc(text)}', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'${tableName}', @level2type=N'COLUMN', @level2name=N'${columnName}';`
    case 'mysql':
      throw new Error('MySQL uses inline comments')
  }
}

/**
 * ⚠️ `tableOptions` 는 **옵셔널이라 빠뜨려도 조용히 동작한다.** 그래서 호출처 둘(웹
 * `export-dialog.tsx` · CLI `export.ts`)의 배선을 **각각** 잠그는 테스트가 따로 있다 —
 * core 테스트만으로는 절대 안 잡힌다(설계 §5.4·§8.2).
 */
export function generateDdl(
  model: ProjectModel, dialect: Dialect, scope: DdlScope = { kind: 'all' }, rules: NamingRules,
  tableOptions?: TableOptions,
): string {
  const tables = selectTables(model, scope, rules).filter(
    (t) => tableColumns(model, t.id).length > 0 && !hasEmptyPhysicalName(model, t, rules),
  )
  const selectedIds = new Set(tables.map((t) => t.id))

  const createBlocks = tables.map((table) => createTableBlock(model, table, dialect, rules, tableOptions))
  const fk = fkStatements(model, selectedIds, dialect, rules).join('\n')
  const index = indexStatements(model, selectedIds, dialect, rules).join('\n')
  const comment = dialect === 'mysql' ? '' : commentStatements(model, tables, dialect, rules).join('\n')

  const header = serializeNameMeta(buildNameMeta(model, tables, rules), '--')
  const body = [createBlocks.join('\n\n'), fk, index, comment]
    .filter((s) => s.trim() !== '').join('\n\n')
  return header === null ? body : `${header}\n${body}`
}

/** DDL 생성 시 사용자가 알아야 할 경고 목록(0컬럼 제외, 타입 변환 등). scope를 반영한다. */
export function ddlWarnings(
  model: ProjectModel, dialect: Dialect, scope: DdlScope = { kind: 'all' }, rules: NamingRules,
): string[] {
  const inScope = selectTables(model, scope, rules)
  const out: string[] = []
  for (const t of inScope) {
    if (tableColumns(model, t.id).length === 0) out.push(`${warningLabel(t, model, rules)}: 컬럼이 없어 내보내기에서 제외됨`)
  }
  for (const t of inScope) {
    if (!hasEmptyPhysicalName(model, t, rules)) continue
    out.push(`${warningLabel(t, model, rules)}: 물리명이 비어 있어 내보내기에서 제외됨`)
  }
  for (const t of inScope) {
    for (const c of tableColumns(model, t.id)) {
      // ⚠️ **해석된 컬럼**을 본다 — 예전에는 `resolveColumnType(c.type, …)` 로 컬럼 자신의
      // 문자열을 봐서 도메인을 지정한 컬럼의 경고가 통째로 빠졌다(설계 §3.4 다).
      // 방언별 물리 타입 오버라이드가 있으면 `resolveColumn` 이 경고를 내지 않는다 —
      // 사용자가 고른 물리 타입의 범위를 우리가 알 수 없으므로 그것이 맞다.
      const { warning } = resolveColumn(c, model, dialect)
      if (warning) out.push(`${composeTablePhysicalName(t, model, rules)}.${c.physicalName}: ${warning}`)
    }
  }
  return out
}
