import type { Column, ProjectModel, Relationship, Table } from './model.js'
import { resolveColumnType, type Dialect } from './dialect.js'
import { parseLogicalType } from './logical-type.js'
import { quoteIdentifier } from './identifier.js'
import { resolveColumn } from './domain-resolve.js'

export type DdlScope =
  | { kind: 'all' }
  | { kind: 'group'; groupId: string }
  | { kind: 'tables'; tableIds: string[] }

const INT_KINDS = new Set(['SMALLINT', 'INT', 'BIGINT'])

function isIntegerType(type: string): boolean {
  const p = parseLogicalType(type)
  return p.ok && INT_KINDS.has(p.type.kind)
}

function autoIncrementToken(dialect: Dialect): string {
  switch (dialect) {
    case 'postgresql':
    case 'oracle':
      return 'GENERATED BY DEFAULT AS IDENTITY'
    case 'mysql':
      return 'AUTO_INCREMENT'
    case 'mssql':
      return 'IDENTITY(1,1)'
  }
}

function selectTables(model: ProjectModel, scope: DdlScope): Table[] {
  const all = Object.values(model.tables)
  let picked: Table[]
  if (scope.kind === 'all') picked = all
  else if (scope.kind === 'group') picked = all.filter((t) => t.groupId === scope.groupId)
  else {
    const ids = new Set(scope.tableIds)
    picked = all.filter((t) => ids.has(t.id))
  }
  return picked.sort((a, b) => a.physicalName.localeCompare(b.physicalName))
}

function tableColumns(model: ProjectModel, tableId: string): Column[] {
  return Object.values(model.columns).filter((c) => c.tableId === tableId).sort((a, b) => a.order - b.order)
}

/** logicalName/physicalName/comment로부터 코멘트 텍스트 산출. 논리명==물리명이고 설명이 없으면 생략(null). */
function commentText(logicalName: string, physicalName: string, comment: string | null): string | null {
  const parts: string[] = []
  if (logicalName && logicalName !== physicalName) parts.push(logicalName)
  else if (logicalName && logicalName === physicalName && comment) parts.push(logicalName)
  if (comment) parts.push(comment)
  if (parts.length === 0) return null
  return parts.join(' - ')
}

const esc = (s: string) => s.replace(/'/g, "''")

function fkBaseName(rel: { name: string | null }, child: string, parent: string): string {
  return rel.name && rel.name.trim() !== '' ? rel.name : `FK_${child}_${parent}`
}

/** 배치 안에서 제약명이 유일하도록 보장한다(충돌 시 _2, _3… 접미). */
function uniqueConstraintName(base: string, used: Set<string>): string {
  if (!used.has(base)) { used.add(base); return base }
  let n = 2
  while (used.has(`${base}_${n}`)) n++
  const name = `${base}_${n}`
  used.add(name)
  return name
}

function columnLine(model: ProjectModel, col: Column, dialect: Dialect): string {
  const r = resolveColumn(col, model, dialect)
  const parts = [quoteIdentifier(col.physicalName, dialect), r.sql]
  const auto = col.autoIncrement && col.isPk && isIntegerType(r.logicalType)
  if (auto) parts.push(autoIncrementToken(dialect))
  if (!col.nullable) parts.push('NOT NULL')
  if (!auto && r.defaultValue !== null && r.defaultValue !== '') parts.push(`DEFAULT ${r.defaultValue}`)
  if (r.checkValues && r.checkValues.length > 0) {
    const list = r.checkValues.map((v) => `'${esc(v)}'`).join(', ')
    parts.push(`CHECK (${quoteIdentifier(col.physicalName, dialect)} IN (${list}))`)
  }
  if (dialect === 'mysql') {
    const text = commentText(col.logicalName, col.physicalName, col.comment)
    if (text !== null) parts.push(`COMMENT '${esc(text)}'`)
  }
  return `  ${parts.join(' ')}`
}

function createTableBlock(model: ProjectModel, table: Table, dialect: Dialect): string {
  const cols = tableColumns(model, table.id)
  const lines = cols.map((c) => columnLine(model, c, dialect))
  const pks = cols.filter((c) => c.isPk)
  if (pks.length > 0) lines.push(`  PRIMARY KEY (${pks.map((c) => quoteIdentifier(c.physicalName, dialect)).join(', ')})`)
  let block = `CREATE TABLE ${quoteIdentifier(table.physicalName, dialect)} (\n${lines.join(',\n')}\n)`
  if (dialect === 'mysql') {
    const text = commentText(table.logicalName, table.physicalName, table.comment)
    if (text !== null) block += ` COMMENT '${esc(text)}'`
  }
  return `${block};`
}

function selectedRelationships(model: ProjectModel, selectedIds: Set<string>): Relationship[] {
  return Object.values(model.relationships).filter(
    (r) => selectedIds.has(r.parentTableId) && selectedIds.has(r.childTableId),
  )
}

function fkStatements(model: ProjectModel, selectedIds: Set<string>, dialect: Dialect): string[] {
  const rels = selectedRelationships(model, selectedIds)
  const statements: string[] = []
  const used = new Set<string>() // 원문 기준 유일성 추적, 출력 시 인용
  const q = (s: string) => quoteIdentifier(s, dialect)
  for (const rel of rels) {
    const parent = model.tables[rel.parentTableId]
    const child = model.tables[rel.childTableId]
    if (!parent || !child) continue
    const rawChildCols = rel.columnMappings.map((m) => model.columns[m.childColumnId]?.physicalName ?? '')
    const childCols = rawChildCols.map(q)
    const parentCols = rel.columnMappings.map((m) => q(model.columns[m.parentColumnId]?.physicalName ?? ''))
    const name = uniqueConstraintName(fkBaseName(rel, child.physicalName, parent.physicalName), used)
    statements.push(
      `ALTER TABLE ${q(child.physicalName)} ADD CONSTRAINT ${q(name)} FOREIGN KEY (${childCols.join(', ')}) REFERENCES ${q(parent.physicalName)} (${parentCols.join(', ')});`,
    )
    if (rel.cardinality === '1:1') {
      const uqName = uniqueConstraintName(`UQ_${child.physicalName}_${rawChildCols.join('_')}`, used)
      statements.push(`ALTER TABLE ${q(child.physicalName)} ADD CONSTRAINT ${q(uqName)} UNIQUE (${childCols.join(', ')});`)
    }
  }
  return statements
}

function indexStatements(model: ProjectModel, selectedIds: Set<string>, dialect: Dialect): string[] {
  const indexes = Object.values(model.indexes).filter((ix) => selectedIds.has(ix.tableId))
  const q = (s: string) => quoteIdentifier(s, dialect)
  return indexes.map((ix) => {
    const table = model.tables[ix.tableId]
    const tableName = table ? table.physicalName : ix.tableId
    const cols = ix.columns
      .map((c) => {
        const col = model.columns[c.columnId]
        const colName = col ? col.physicalName : c.columnId
        return `${q(colName)} ${c.direction.toUpperCase()}`
      })
      .join(', ')
    const uniqueToken = ix.unique ? 'UNIQUE ' : ''
    return `CREATE ${uniqueToken}INDEX ${q(ix.name)} ON ${q(tableName)} (${cols});`
  })
}

function commentStatements(model: ProjectModel, tables: Table[], dialect: Dialect): string[] {
  const statements: string[] = []
  for (const table of tables) {
    const tableText = commentText(table.logicalName, table.physicalName, table.comment)
    if (tableText !== null) statements.push(tableCommentStatement(dialect, table.physicalName, tableText))
    const cols = tableColumns(model, table.id)
    for (const col of cols) {
      const colText = commentText(col.logicalName, col.physicalName, col.comment)
      if (colText !== null) statements.push(columnCommentStatement(dialect, table.physicalName, col.physicalName, colText))
    }
  }
  return statements
}

function tableCommentStatement(dialect: Dialect, tableName: string, text: string): string {
  switch (dialect) {
    case 'postgresql':
    case 'oracle':
      return `COMMENT ON TABLE ${quoteIdentifier(tableName, dialect)} IS '${esc(text)}';`
    case 'mssql':
      return `EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'${esc(text)}', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'${tableName}';`
    case 'mysql':
      throw new Error('MySQL uses inline comments')
  }
}

function columnCommentStatement(dialect: Dialect, tableName: string, columnName: string, text: string): string {
  switch (dialect) {
    case 'postgresql':
    case 'oracle':
      return `COMMENT ON COLUMN ${quoteIdentifier(tableName, dialect)}.${quoteIdentifier(columnName, dialect)} IS '${esc(text)}';`
    case 'mssql':
      return `EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'${esc(text)}', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'${tableName}', @level2type=N'COLUMN', @level2name=N'${columnName}';`
    case 'mysql':
      throw new Error('MySQL uses inline comments')
  }
}

export function generateDdl(model: ProjectModel, dialect: Dialect, scope: DdlScope = { kind: 'all' }): string {
  const tables = selectTables(model, scope).filter((t) => tableColumns(model, t.id).length > 0)
  const selectedIds = new Set(tables.map((t) => t.id))

  const createBlocks = tables.map((table) => createTableBlock(model, table, dialect))
  const fk = fkStatements(model, selectedIds, dialect).join('\n')
  const index = indexStatements(model, selectedIds, dialect).join('\n')
  const comment = dialect === 'mysql' ? '' : commentStatements(model, tables, dialect).join('\n')

  return [createBlocks.join('\n\n'), fk, index, comment].filter((s) => s.trim() !== '').join('\n\n')
}

/** DDL 생성 시 사용자가 알아야 할 경고 목록(0컬럼 제외, 타입 변환 등). scope를 반영한다. */
export function ddlWarnings(model: ProjectModel, dialect: Dialect, scope: DdlScope = { kind: 'all' }): string[] {
  const inScope = selectTables(model, scope)
  const out: string[] = []
  for (const t of inScope) {
    if (tableColumns(model, t.id).length === 0) out.push(`${t.physicalName}: 컬럼이 없어 DDL에서 제외됨`)
  }
  for (const t of inScope) {
    for (const c of tableColumns(model, t.id)) {
      const { warning } = resolveColumnType(c.type, dialect)
      if (warning) out.push(`${t.physicalName}.${c.physicalName}: ${warning}`)
    }
  }
  return out
}
